#!/usr/bin/env python
"""Curate the deterministic, rights-reviewed public OIPS data snapshot."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

import pandas as pd


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT / "src"))

from oips_repro.io import ENCODING, LINE_TERMINATOR, write_stable_csv  # noqa: E402
from public_data_inventory import EXTERNAL_COLUMNS, build_external_inventory  # noqa: E402
from public_data_tables import (  # noqa: E402
    DECISION_COLUMNS,
    FEATURE_COLUMNS,
    LEGACY_COLUMNS,
    MD_COLUMNS,
    REDOCKING_COLUMNS,
    REFERENCE_COLUMNS,
    SYSTEM_COLUMNS,
    build_features,
    build_legacy_crosswalk,
    build_manual_decisions,
    build_md_evidence,
    build_redocking_evidence,
    build_reference_annotations,
    build_structure_index,
    build_systems,
    read_source_csv,
)


RIGHTS_COLUMNS = [
    "asset_class",
    "scientific_role",
    "source_provider",
    "content_scope",
    "repository_action",
    "review_status",
    "license_scope",
    "terms_or_evidence_url",
    "approval_basis",
    "review_date",
    "notes",
]
MANIFEST_COLUMNS = [
    "asset_id",
    "scientific_role",
    "local_path_or_url",
    "repository",
    "persistent_id",
    "sha256",
    "bytes",
    "media_type",
    "license_or_terms",
    "access_status",
    "source_version_or_date",
]
LOCAL_ROLES = {
    "release documentation",
    "system metadata table",
    "curation audit metadata",
    "normalized pocket features",
    "reference annotations",
    "MD post-hoc summary",
    "redocking post-hoc summary",
    "external archive inventory",
    "prepared paired structure",
    "legacy cluster crosswalk",
}
EXTERNAL_ROLES = {
    "full MD inputs",
    "full MD trajectories",
    "restart or checkpoint files",
    "representative MD snapshots",
    "large raw pocket outputs",
}
SOURCE_FILES = {
    "features": Path("zhu-pack/pack/output/oips/oips_pocket_features.csv"),
    "structures": Path("zhu-pack/pack/pdb_manifest.autogenerated.csv"),
    "systems": Path(
        "OIPS_FINAL_ANALYSIS/00_configuration/pocket_category_mapping.csv"
    ),
    "references": Path("zhu-pack/pack/output/oips/oips_target_summary.csv"),
    "md": Path(
        "OIPS_FINAL_ANALYSIS/06_md_conflict/md_static_dynamic_mapping_all_targets.csv"
    ),
    "redocking": Path(
        "OIPS_FINAL_ANALYSIS/07_redocking/redocking_complete_summary.csv"
    ),
    "legacy": Path("zhu-pack/pack/output/oips/oips_s2_current_cluster_scores.csv"),
    "crosswalk": Path(
        "OIPS_FINAL_ANALYSIS_0711/working_cluster_to_cluster_v2_mapping.csv"
    ),
    "representative": Path(
        "OIPS_FINAL_ANALYSIS_0711/representative_case_results.csv"
    ),
    "claim_evidence": Path("OIPS_FINAL_ANALYSIS_0711/claim_evidence_matrix.csv"),
}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare the rights-reviewed public OIPS data snapshot."
    )
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--destination-root", type=Path, required=True)
    parser.add_argument("--rights-policy", type=Path, required=True)
    parser.add_argument(
        "--audit-only",
        action="store_true",
        help="Discover sources and validate rights without writing release payloads.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace existing managed outputs after the rights audit succeeds.",
    )
    return parser.parse_args(argv)


def resolve_policy_path(policy: Path, destination_root: Path) -> Path:
    if policy.is_absolute():
        return policy.resolve(strict=True)
    destination_candidate = (destination_root / policy).resolve(strict=False)
    cwd_candidate = (Path.cwd() / policy).resolve(strict=False)
    for candidate in [destination_candidate, cwd_candidate]:
        if candidate.is_file():
            return candidate.resolve(strict=True)
    raise FileNotFoundError(f"rights policy is missing: {policy}")


def read_rights_policy(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path, sep="\t", keep_default_na=False, dtype=str)
    if list(frame.columns) != RIGHTS_COLUMNS:
        raise ValueError("rights policy does not match the approved exact schema")
    if frame.empty or not frame["asset_class"].is_unique:
        raise ValueError("rights policy requires unique, nonempty asset classes")
    required_text = [
        "asset_class",
        "scientific_role",
        "source_provider",
        "content_scope",
        "repository_action",
        "review_status",
        "license_scope",
        "terms_or_evidence_url",
        "approval_basis",
        "review_date",
    ]
    if frame[required_text].apply(lambda column: column.str.strip().eq("")).any().any():
        raise ValueError("rights policy contains an empty required evidence field")
    return frame


def audit_rights(rights: pd.DataFrame) -> dict[str, dict[str, str]]:
    duplicated_roles = rights[rights["scientific_role"].duplicated(keep=False)]
    if not duplicated_roles.empty:
        raise ValueError("rights policy scientific_role values must be unique")
    by_role = rights.set_index("scientific_role", drop=False).to_dict("index")
    missing_local = sorted(LOCAL_ROLES - set(by_role))
    missing_external = sorted(EXTERNAL_ROLES - set(by_role))
    if missing_local or missing_external:
        raise ValueError(
            f"rights policy is missing proposed roles: {missing_local + missing_external}"
        )
    for role in LOCAL_ROLES:
        row = by_role[role]
        if row["review_status"] != "approved_for_repository":
            raise PermissionError(f"local asset role is not approved: {role}")
        if row["repository_action"] != "commit_local_payload":
            raise PermissionError(f"local asset role is not eligible for copying: {role}")
        if not row["license_scope"].strip() or not row["terms_or_evidence_url"].strip():
            raise PermissionError(f"local asset role lacks terms evidence: {role}")
    for role in EXTERNAL_ROLES:
        row = by_role[role]
        if row["review_status"] not in {"manifest_only", "excluded"}:
            raise PermissionError(f"external/raw asset role has unsafe review status: {role}")
        if row["repository_action"] == "commit_local_payload":
            raise PermissionError(f"external/raw asset role cannot be copied: {role}")
    return by_role


def load_and_build(source_root: Path, destination_root: Path) -> dict[str, object]:
    sources: dict[str, pd.DataFrame] = {}
    for name, relative in SOURCE_FILES.items():
        path = source_root / relative
        if name == "claim_evidence":
            if not path.is_file():
                raise FileNotFoundError(f"required decision evidence is missing: {path}")
            continue
        sources[name] = read_source_csv(path)
    structure_manifest_path = source_root / SOURCE_FILES["structures"]
    structures = build_structure_index(
        sources["structures"], manifest_path=structure_manifest_path
    )
    return {
        "source_frames": sources,
        "features": build_features(sources["features"]),
        "structures": structures,
        "structure_manifest_path": structure_manifest_path,
        "systems": build_systems(sources["systems"], structures),
        "references": build_reference_annotations(sources["references"]),
        "md": build_md_evidence(sources["md"]),
        "redocking": build_redocking_evidence(sources["redocking"]),
        "legacy": build_legacy_crosswalk(sources["legacy"], sources["crosswalk"]),
        "decisions": build_manual_decisions(
            sources["systems"], destination_root, sources["representative"]
        ),
        "external": build_external_inventory(
            sources["features"], sources["md"], source_root
        ),
    }


def structure_destinations(
    structures: pd.DataFrame, structure_manifest_path: Path, destination_root: Path
) -> list[tuple[str, Path, Path]]:
    planned: list[tuple[str, Path, Path]] = []
    for row in structures.sort_values("pdb_id").itertuples(index=False):
        source = structure_manifest_path.parent / Path(row.paired_structure)
        destination = (
            destination_root
            / "data"
            / "structures"
            / f"{row.pdb_id.lower()}_paired{source.suffix.lower()}"
        )
        if source.stat().st_size > 10 * 1024 * 1024:
            raise ValueError(f"structure exceeds 10 MiB Git limit: {row.pdb_id}")
        planned.append((row.pdb_id, source, destination))
    return planned


def managed_output_paths(
    destination_root: Path, structure_plan: list[tuple[str, Path, Path]]
) -> list[Path]:
    relative = [
        "data/README.md",
        "data/metadata/systems.tsv",
        "data/metadata/manual_decisions.tsv",
        "data/static/tool_pocket_features.csv",
        "data/posthoc/reference_annotations.csv",
        "data/posthoc/md_evidence.csv",
        "data/posthoc/redocking_evidence.csv",
        "data/external_archive_manifest.tsv",
        "data/manifest.tsv",
        "data/SHA256SUMS",
        "legacy/working-cluster-to-cluster-v2.csv",
    ]
    return [destination_root / path for path in relative] + [
        destination for _, _, destination in structure_plan
    ]


def expected_local_payload_paths(
    destination_root: Path, structure_plan: list[tuple[str, Path, Path]]
) -> set[Path]:
    fixed = {
        destination_root / "data/README.md",
        destination_root / "data/metadata/systems.tsv",
        destination_root / "data/metadata/asset-rights.tsv",
        destination_root / "data/metadata/manual_decisions.tsv",
        destination_root / "data/static/tool_pocket_features.csv",
        destination_root / "data/posthoc/reference_annotations.csv",
        destination_root / "data/posthoc/md_evidence.csv",
        destination_root / "data/posthoc/redocking_evidence.csv",
        destination_root / "data/external_archive_manifest.tsv",
    }
    return {path.resolve(strict=False) for path in fixed} | {
        destination.resolve(strict=False) for _, _, destination in structure_plan
    }


def assert_no_unmanaged_payload(
    destination_root: Path, reviewed_payload_paths: set[Path]
) -> None:
    data_root = (destination_root / "data").resolve(strict=False)
    controls = {
        (data_root / "manifest.tsv").resolve(strict=False),
        (data_root / "SHA256SUMS").resolve(strict=False),
    }
    allowed = {path.resolve(strict=False) for path in reviewed_payload_paths} | controls
    existing = {
        path.resolve(strict=False)
        for path in data_root.rglob("*")
        if path.is_file()
    } if data_root.exists() else set()
    unexpected = sorted(existing - allowed, key=lambda path: path.as_posix())
    if unexpected:
        display = ", ".join(path.relative_to(destination_root).as_posix() for path in unexpected[:5])
        raise ValueError(
            f"unmanaged data payload detected ({len(unexpected)} file(s)): {display}"
        )


def assert_no_collisions(paths: list[Path], force: bool) -> None:
    collisions = [path for path in paths if path.exists()]
    if collisions and not force:
        display = ", ".join(path.as_posix() for path in collisions[:5])
        raise FileExistsError(
            f"refusing to overwrite {len(collisions)} managed output(s): {display}; use --force"
        )


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding=ENCODING, newline="") as handle:
        handle.write(text.replace("\r\n", "\n").replace("\r", "\n"))


def write_readme(path: Path) -> None:
    content = """# Public OIPS data snapshot

This directory contains the reviewed 1,742-record, 21-target public input snapshot for the OIPS reproducibility workflow.

`static/tool_pocket_features.csv` is the allow-listed detector feature table. `metadata/systems.tsv` records approved project annotations and leaves unverified preparation or simulation metadata explicitly unavailable. The post-hoc tables contain only fields consumed by public analyses. Prepared paired structures are provided under stable lowercase names.

`metadata/asset-rights.tsv` is the redistribution gate. Raw service packages, full molecular-dynamics artifacts, checkpoints, and licensed binary formats are not Git payloads; their availability is represented only by stable labels in `external_archive_manifest.tsv`. `metadata/manual_decisions.tsv` records reviewed corrections, annotations, parameter freezing, and representative-case selections.

`manifest.tsv` records every local file in this directory except itself and `SHA256SUMS`; the checksum file then covers every other file, including both manifests. Empty numeric fields mean unavailable source values. Tables use UTF-8, LF endings, lowercase booleans, and deterministic stable sorting.
"""
    write_text(path, content)


def write_tables(destination_root: Path, built: dict[str, object]) -> None:
    write_readme(destination_root / "data" / "README.md")
    write_stable_csv(
        built["features"],
        destination_root / "data/static/tool_pocket_features.csv",
        columns=FEATURE_COLUMNS,
        sort_by=["pdb_id", "tool", "row_id"],
    )
    write_stable_csv(
        built["systems"],
        destination_root / "data/metadata/systems.tsv",
        columns=SYSTEM_COLUMNS,
        sort_by=["pdb_id"],
        delimiter="\t",
    )
    write_stable_csv(
        built["decisions"],
        destination_root / "data/metadata/manual_decisions.tsv",
        columns=DECISION_COLUMNS,
        sort_by=["decision_id"],
        delimiter="\t",
    )
    write_stable_csv(
        built["references"],
        destination_root / "data/posthoc/reference_annotations.csv",
        columns=REFERENCE_COLUMNS,
        sort_by=["pdb_id"],
    )
    write_stable_csv(
        built["md"],
        destination_root / "data/posthoc/md_evidence.csv",
        columns=MD_COLUMNS,
        sort_by=["pdb_id", "Simulation_context", "MD_run"],
    )
    write_stable_csv(
        built["redocking"],
        destination_root / "data/posthoc/redocking_evidence.csv",
        columns=REDOCKING_COLUMNS,
        sort_by=["pdb_id"],
    )
    write_stable_csv(
        built["legacy"],
        destination_root / "legacy/working-cluster-to-cluster-v2.csv",
        columns=LEGACY_COLUMNS,
        sort_by=["pdb_id", "working_cluster_id", "cluster_v2_id"],
    )
    write_stable_csv(
        built["external"],
        destination_root / "data/external_archive_manifest.tsv",
        columns=EXTERNAL_COLUMNS,
        sort_by=["asset_id"],
        delimiter="\t",
    )


def copy_structures(structure_plan: list[tuple[str, Path, Path]]) -> None:
    for _, source, destination in structure_plan:
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def role_and_asset_id(relative: str) -> tuple[str, str]:
    fixed = {
        "data/README.md": ("release documentation", "data-readme"),
        "data/metadata/systems.tsv": ("system metadata table", "metadata-systems"),
        "data/metadata/asset-rights.tsv": (
            "curation audit metadata",
            "metadata-asset-rights",
        ),
        "data/metadata/manual_decisions.tsv": (
            "curation audit metadata",
            "metadata-manual-decisions",
        ),
        "data/static/tool_pocket_features.csv": (
            "normalized pocket features",
            "static-tool-pocket-features",
        ),
        "data/posthoc/reference_annotations.csv": (
            "reference annotations",
            "posthoc-reference-annotations",
        ),
        "data/posthoc/md_evidence.csv": ("MD post-hoc summary", "posthoc-md-evidence"),
        "data/posthoc/redocking_evidence.csv": (
            "redocking post-hoc summary",
            "posthoc-redocking-evidence",
        ),
        "data/external_archive_manifest.tsv": (
            "external archive inventory",
            "external-archive-manifest",
        ),
    }
    if relative in fixed:
        return fixed[relative]
    if relative.startswith("data/structures/"):
        pdb_id = Path(relative).stem.split("_", 1)[0].lower()
        return "prepared paired structure", f"structure-{pdb_id}"
    raise ValueError(f"unclassified local payload path: {relative}")


def media_type(path: Path) -> str:
    if path.name == "README.md":
        return "text/markdown"
    if path.suffix == ".tsv":
        return "text/tab-separated-values"
    if path.suffix == ".csv":
        return "text/csv"
    if path.suffix == ".pdb":
        return "chemical/x-pdb"
    if path.suffix == ".cif":
        return "chemical/x-mmcif"
    return "application/octet-stream"


def build_manifest(
    destination_root: Path,
    rights_by_role: dict[str, dict[str, str]],
    reviewed_payload_paths: set[Path],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for path in sorted(reviewed_payload_paths, key=lambda item: item.as_posix()):
        if not path.is_file():
            raise FileNotFoundError(f"reviewed local payload was not written: {path}")
        relative = path.relative_to(destination_root).as_posix()
        role, asset_id = role_and_asset_id(relative)
        rights = rights_by_role[role]
        persistent_id = "not_assigned"
        source_version = "curated_snapshot_2026-07-17"
        if role == "prepared paired structure":
            pdb_id = asset_id.removeprefix("structure-").upper()
            persistent_id = f"https://doi.org/10.2210/pdb{pdb_id}/pdb"
            source_version = "not_available_in_source_materials"
        rows.append(
            {
                "asset_id": asset_id,
                "scientific_role": role,
                "local_path_or_url": relative,
                "repository": "GitHub repository",
                "persistent_id": persistent_id,
                "sha256": sha256(path),
                "bytes": path.stat().st_size,
                "media_type": media_type(path),
                "license_or_terms": rights["license_scope"],
                "access_status": "repository_local",
                "source_version_or_date": source_version,
            }
        )
    output = pd.DataFrame(rows, columns=MANIFEST_COLUMNS)
    if output.empty or not output["asset_id"].is_unique:
        raise ValueError("local manifest requires unique asset IDs")
    return output


def write_checksums(destination_root: Path, reviewed_payload_paths: set[Path]) -> None:
    checksum_path = destination_root / "data" / "SHA256SUMS"
    paths = sorted(
        [*reviewed_payload_paths, destination_root / "data/manifest.tsv"],
        key=lambda item: item.relative_to(destination_root).as_posix(),
    )
    lines = [
        f"{sha256(path)}  {path.relative_to(destination_root).as_posix()}"
        for path in paths
    ]
    write_text(checksum_path, LINE_TERMINATOR.join(lines) + LINE_TERMINATOR)


def ensure_size_limit(destination_root: Path) -> None:
    oversized = [
        path
        for path in (destination_root / "data").rglob("*")
        if path.is_file() and path.stat().st_size > 10 * 1024 * 1024
    ]
    if oversized:
        raise ValueError(f"released file exceeds 10 MiB: {oversized[0]}")


def run(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    source_root = args.source_root.resolve(strict=True)
    destination_root = args.destination_root.resolve(strict=True)
    policy_path = resolve_policy_path(args.rights_policy, destination_root)
    expected_policy = (destination_root / "data/metadata/asset-rights.tsv").resolve(
        strict=False
    )
    if policy_path != expected_policy:
        raise ValueError("rights policy must be the released data/metadata/asset-rights.tsv")

    rights = read_rights_policy(policy_path)
    built = load_and_build(source_root, destination_root)
    rights_by_role = audit_rights(rights)
    structure_plan = structure_destinations(
        built["structures"], built["structure_manifest_path"], destination_root
    )
    summary = {
        "records": len(built["features"]),
        "targets": built["features"]["pdb_id"].nunique(),
        "structures": len(structure_plan),
    }
    if args.audit_only:
        print(json.dumps(summary, separators=(",", ":")))
        return 0

    reviewed_payload_paths = expected_local_payload_paths(
        destination_root, structure_plan
    )
    assert_no_unmanaged_payload(destination_root, reviewed_payload_paths)
    assert_no_collisions(managed_output_paths(destination_root, structure_plan), args.force)
    write_tables(destination_root, built)
    copy_structures(structure_plan)
    manifest = build_manifest(
        destination_root, rights_by_role, reviewed_payload_paths
    )
    write_stable_csv(
        manifest,
        destination_root / "data/manifest.tsv",
        columns=MANIFEST_COLUMNS,
        sort_by=["asset_id"],
        delimiter="\t",
    )
    write_checksums(destination_root, reviewed_payload_paths)
    assert_no_unmanaged_payload(destination_root, reviewed_payload_paths)
    ensure_size_limit(destination_root)
    print(json.dumps(summary, separators=(",", ":")))
    return 0


def main() -> None:
    try:
        raise SystemExit(run())
    except (FileExistsError, FileNotFoundError, PermissionError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc


if __name__ == "__main__":
    main()
