import sys
from pathlib import Path

import pandas as pd
import pytest


ROOT = Path(__file__).parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from public_data_tables import build_manual_decisions, build_structure_index
import prepare_public_data


def test_structure_manifest_paths_resolve_from_the_manifest_directory(tmp_path: Path):
    manifest_path = tmp_path / "zhu-pack" / "pack" / "pdb_manifest.autogenerated.csv"
    rows = []
    for index in range(21):
        pdb_id = f"{index + 1:04d}"
        relative = Path("pdb-resource") / pdb_id / f"{pdb_id}-p.pdb"
        source = manifest_path.parent / relative
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text("ATOM\n", encoding="utf-8")
        rows.append({"pdb_id": pdb_id, "paired_structure": relative.as_posix()})

    result = build_structure_index(pd.DataFrame(rows), manifest_path=manifest_path)

    assert len(result) == 21


def test_manual_audit_contains_21_categories_reference_parameters_and_three_cases(
    tmp_path: Path,
):
    categories = pd.DataFrame(
        [
            {
                "pdb_id": f"{index + 1:04d}",
                "Initial_pocket_annotation": f"annotation-{index}",
                "Pocket_category": "orthosteric",
                "Category_mapping_status": "reviewed",
            }
            for index in range(21)
        ]
    )
    config = tmp_path / "config" / "manuscript.yaml"
    config.parent.mkdir(parents=True)
    config.write_text("clustering:\n  distance: 12.0\n", encoding="utf-8")
    representative = pd.DataFrame({"pdb_id": ["5J89", "5TBM", "4W9H"]})

    result = build_manual_decisions(categories, tmp_path, representative)

    assert len(result) == 26


def test_curator_reports_overwrite_refusal_without_a_traceback(monkeypatch, capsys):
    def refuse(_argv=None):
        raise FileExistsError("refusing to overwrite managed outputs; use --force")

    monkeypatch.setattr(prepare_public_data, "run", refuse)

    with pytest.raises(SystemExit) as exit_info:
        prepare_public_data.main()

    assert exit_info.value.code == 2
    assert capsys.readouterr().err == (
        "error: refusing to overwrite managed outputs; use --force\n"
    )


def test_curator_rejects_unmanaged_files_before_manifesting_them(tmp_path: Path):
    checker = getattr(prepare_public_data, "assert_no_unmanaged_payload", None)
    assert checker is not None, "curator needs an explicit unmanaged-payload gate"
    reviewed_policy = tmp_path / "data" / "metadata" / "asset-rights.tsv"
    reviewed_policy.parent.mkdir(parents=True)
    reviewed_policy.write_text("reviewed\n", encoding="utf-8")
    stale = tmp_path / "data" / "structures" / "stale_paired.pdb"
    stale.parent.mkdir(parents=True)
    stale.write_text("ATOM\n", encoding="utf-8")

    with pytest.raises(ValueError, match="unmanaged data payload"):
        checker(tmp_path, {reviewed_policy})
